name: busapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.18
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animated_check: ^1.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  sign_in_with_apple: 6.1.4
  sign_in_with_apple_web: 2.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bienvenida.png
    - lib/assets/success.png
    - lib/assets/google.png
    - lib/assets/bus_icon.png
